export const GET_USER_INFO_LOADING = "GET_USER_INFO_LOADING";
export const GET_USER_INFO_SUCCESS = "GET_USER_INFO_SUCCESS";
export const GET_USER_INFO_FAILED = "GET_USER_INFO_FAILED";

export const GET_POST_COMMENTS_LOADING = "GET_POST_COMMENTS_LOADING";
export const GET_POST_COMMENTS_SUCCESS = "GET_POST_COMMENTS_SUCCESS";
export const GET_POST_COMMENTS_FAILED = "GET_POST_COMMENTS_FAILED";
